import = ["~/.config/alacritty/themes/themes/challenger_deep.yaml"]

[window]
opacity = 0.85
dimensions = { columns = 220, lines = 70 }
padding = { x = 12, y = 12 }

[scrolling]
history = 10_000

[font]
size = 13.5
normal = { family = "Cica", style = "Regular" }
bold = { family = "Cica", style = "Bold" }
italic = { family = "Cica", style = "Italic" }
bold_italic = { family = "Cica", style = "Bold Italic" }

[shell]
program = "/opt/homebrew/bin/fish"
args = ["-l", "-c", "/opt/homebrew/bin/tmux"]

[[keyboard.bindings]]
key = "Space"
mods = "Alt"
chars = " "

[[keyboard.bindings]]
key = "Back"
mods = "Super"
chars = "\u0015"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bOH"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bOF"
mode = "AppCursor"
